# Project information
site_name: Algorithm in Action
site_url: https://vveicc.github.io/algorithm-in-action
site_author: vveicc

# Repository
repo_name: vveicc/algorithm-in-action
repo_url: https://github.com/vveicc/algorithm-in-action
edit_uri: edit/main/docs/

# Copyright
copyright: 2015-2023 &copy; VVEICC

# Contents
nav:
  - 简介:
    - 关于本站: index.md
    - 格式说明: intro/format.md
  - 算法基础:
    - 枚举: basic/enumerate.md
    - 模拟: basic/simulate.md
    - 递归 & 分治: basic/divide-and-conquer.md
    - 前缀和 & 差分: basic/prefix-sum.md
    - 二分: basic/binary.md
    - 构造: basic/construction.md
    - 双指针: basic/two-pointer.md
  - 数据结构:
    - 单调栈: ds/monotonous-stack.md
    - 树状数组: ds/bit.md
  - 动态规划:
    - 动态规划基础: dp/basic.md
    - 背包 DP: dp/knapsack.md
    - 树形 DP: dp/tree.md
  - 数学:
    - 二进制集合操作: math/binary-set.md
  - 图论:
    - 树上问题:
      - 树的直径: graph/tree/diameter.md
    - 最短路: graph/shortest-path.md

# Configuration
theme:
  name: material
  language: zh
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    - navigation.footer
    - navigation.top
    - search.suggest
    # - search.highlight
    - search.share
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: red
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: teal
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto Slab
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo.svg
  icon:
    admonition:
      # note: octicons/tag-16
      note: octicons/question-16 # for question
      abstract: octicons/checklist-16
      # info: octicons/info-16
      info: octicons/check-circle-16 # for answer
      tip: octicons/light-bulb-16
      success: octicons/check-circle-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: false
      type: date

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: ['code', 'code/basic', 'code/ds', 'code/dp', 'code/math', 'code/graph']

# Customization
extra:
  annotate:
    json: [.s2]
  social:
    - icon: simple/leetcode
      link: https://leetcode.cn/u/vveicc
    - icon: fontawesome/brands/github
      link: https://github.com/vveicc

extra_javascript:
  - javascripts/link.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
